spring:
  datasource:
    url: jdbc:sqlite:${DATASET:db/ijadataset.db}
    driverClassName: org.sqlite.JDBC
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: jp.kusumotolab.InfiniteVarietyExp.sqlite.SQLiteDialect
