spring:
  datasource:
    dataset:
      url: jdbc:sqlite:${DATASET:./db/ijadataset.db}
      driverClassName: org.sqlite.JDBC
      initialization-mode: never
    results:
      url: jdbc:h2:file:${RESULTS:./db/results}
      driverClassName: org.h2.Driver
      username: ${h2user:}
      password: ${h2pass:}
      schema: classpath:schema-results.sql
      data:
      initialization-mode: never

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: INFO
